# Generated by Django 4.0.2 on 2022-02-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='date_of_purchase',
            field=models.CharField(max_length=255, verbose_name='Date of Purchase'),
        ),
    ]
