# Generated by Django 4.0.2 on 2022-02-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_alter_insurancedata_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='date_of_purchase',
            field=models.DateField(auto_now=True, verbose_name='Date of Purchase'),
        ),
    ]
